/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retailpos;

import Clases.Conexion;
import Clases.Formato;
import Clases.Sucursal;
import clases.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Peter
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
       Usuario instUsr = new Usuario(Conexion.CONEXION_USERID_OK);
    
    /**
     * Creates new form frmMenuPrincipal
     * @throws java.sql.SQLException
     */
    public frmMenuPrincipal() throws SQLException {
        initComponents();
        
        this.txtOperador.setText(" OPERADOR : " + instUsr.getUsu_id_usua());
        this.txtSucursal.setText(" SUCURSAL : " + instUsr.getUsu_id_sucu());
        this.txtFormato.setText(" FORMATO : " + instUsr.getUsu_frm_nombre());
        
        if (instUsr.getUsu_id_perf() > 1){
             this.txtPerfil.setText("  "+instUsr.getUsu_per_Nombre());
        }else{
            this.txtPerfil.setText(" PERFIL : " + instUsr.getUsu_per_Nombre());
        }
        
        
        this.txtOperador.setBackground(Color.BLUE);           
        this.txtSucursal.setBackground(Color.BLUE); 
        this.txtFormato.setBackground(Color.BLUE); 
        this.txtPerfil.setBackground(Color.BLUE); 
        
        this.setTitle("    COMERCIO RETAIL ®                     " + instUsr.getUsu_frm_Slogan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txtOperador = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtFormato = new javax.swing.JTextField();
        txtPerfil = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jButton1.setText("GESTION COMERCIAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("STOCK");

        jButton3.setText("CONFIGURACION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("INFORMES");

        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton6.setText("VENTAS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtOperador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtOperador.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtOperador.setEnabled(false);
        txtOperador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtOperadorMouseEntered(evt);
            }
        });
        txtOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperadorActionPerformed(evt);
            }
        });

        txtSucursal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSucursal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtSucursal.setEnabled(false);
        txtSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSucursalMouseEntered(evt);
            }
        });

        txtFormato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFormato.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtFormato.setEnabled(false);
        txtFormato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFormatoMouseEntered(evt);
            }
        });

        txtPerfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtPerfil.setEnabled(false);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField6.setEnabled(false);

        jMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu1.setText("VENTAS");

        jMenuItem1.setText("Cajero Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu3.setText("GESTION COMERCIAL");

        jMenu6.setText("Precios");

        jMenu27.setText("Consulta Precios");

        jMenuItem50.setText("Consulta de Precios");
        jMenu27.add(jMenuItem50);

        jMenuItem51.setText("Consulta de Margen");
        jMenu27.add(jMenuItem51);

        jMenuItem69.setText("Consulta de Rebajas");
        jMenu27.add(jMenuItem69);

        jMenu6.add(jMenu27);

        jMenu28.setText("Cambio Precios");

        jMenuItem74.setText("Cambio de Precios");
        jMenu28.add(jMenuItem74);

        jMenuItem75.setText("Cambio de Margen");
        jMenu28.add(jMenuItem75);

        jMenuItem76.setText("Cambio de Rebajas");
        jMenu28.add(jMenuItem76);

        jMenu6.add(jMenu28);

        jMenu3.add(jMenu6);

        jMenu21.setText("Margenes");

        jMenuItem52.setText("Modificacion por Linea");
        jMenu21.add(jMenuItem52);

        jMenuItem53.setText("Modificacion por Area");
        jMenu21.add(jMenuItem53);

        jMenu3.add(jMenu21);

        jMenu23.setText("Provision");

        jMenuItem54.setText("Carga Locales");
        jMenu23.add(jMenuItem54);

        jMenuItem55.setText("Carga Bodega Central");
        jMenu23.add(jMenuItem55);

        jMenu3.add(jMenu23);

        jMenu25.setText("Promociones");

        jMenu26.setText("Mantenedor");

        jMenuItem71.setText("Creacion Promoción");
        jMenu26.add(jMenuItem71);

        jMenuItem73.setText("Modificacion Promocion");
        jMenu26.add(jMenuItem73);

        jMenu25.add(jMenu26);

        jMenuItem70.setText("Consulta Promociones");
        jMenu25.add(jMenuItem70);

        jMenuItem72.setText("Organizar Promociones");
        jMenu25.add(jMenuItem72);

        jMenuItem77.setText("Asignacion Promociones");
        jMenu25.add(jMenuItem77);

        jMenu3.add(jMenu25);

        jMenuBar1.add(jMenu3);

        jMenu7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu7.setText("STOCK");

        jMenuItem64.setText("Stock por Producto");
        jMenu7.add(jMenuItem64);

        jMenuItem66.setText("Stock por Linea");
        jMenu7.add(jMenuItem66);

        jMenuItem65.setText("Stock por Area");
        jMenu7.add(jMenuItem65);

        jMenuItem68.setText("Stock por Local");
        jMenu7.add(jMenuItem68);

        jMenuItem67.setText("Stock de Inventario");
        jMenu7.add(jMenuItem67);

        jMenuBar1.add(jMenu7);

        jMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu4.setText("CONFIGURACION");

        jMenu9.setText("Formatos");

        jMenuItem2.setText("Agregar Formato");
        jMenu9.add(jMenuItem2);

        jMenuItem3.setText("Modificar Formato");
        jMenu9.add(jMenuItem3);

        jMenuItem4.setText("Consultar Formato");
        jMenu9.add(jMenuItem4);

        jMenuItem5.setText("Listar Formatos");
        jMenu9.add(jMenuItem5);

        jMenu4.add(jMenu9);

        jMenu10.setText("Sucursales");

        jMenuItem14.setText("Agregar Sucursal");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Modificar Sucursal");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenuItem16.setText("Consultar Sucursal");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuItem17.setText("Listar Sucursales");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenu4.add(jMenu10);

        jMenu11.setText("Cajas POS");

        jMenuItem18.setText("Agregar POS");
        jMenu11.add(jMenuItem18);

        jMenuItem19.setText("Modificar POS");
        jMenu11.add(jMenuItem19);

        jMenuItem20.setText("Consultar POS");
        jMenu11.add(jMenuItem20);

        jMenuItem21.setText("Listar POS");
        jMenu11.add(jMenuItem21);

        jMenu4.add(jMenu11);

        jMenu12.setText("Usuarios");

        jMenuItem22.setText("Agregar Usuarios");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem22);

        jMenuItem23.setText("Modificar Usuarios");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem23);

        jMenuItem24.setText("Consultar Usuarios");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem24);

        jMenuItem25.setText("Listar Usuarios");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem25);

        jMenu4.add(jMenu12);

        jMenu13.setText("Productos");

        jMenuItem26.setText("Agregar Productos");
        jMenu13.add(jMenuItem26);

        jMenuItem27.setText("Modificar Productos");
        jMenu13.add(jMenuItem27);

        jMenuItem28.setText("Consultar Productos");
        jMenu13.add(jMenuItem28);

        jMenuItem29.setText("Listar Productos");
        jMenu13.add(jMenuItem29);

        jMenu4.add(jMenu13);

        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu5.setText("INFORMES");

        jMenu15.setText("Informe Cajeros");

        jMenuItem6.setText("jMenuItem6");
        jMenu15.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu15.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu15.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        jMenu15.add(jMenuItem9);

        jMenu5.add(jMenu15);

        jMenu16.setText("Informe Ventas ");

        jMenuItem10.setText("jMenuItem6");
        jMenu16.add(jMenuItem10);

        jMenuItem31.setText("jMenuItem7");
        jMenu16.add(jMenuItem31);

        jMenuItem32.setText("jMenuItem8");
        jMenu16.add(jMenuItem32);

        jMenuItem33.setText("jMenuItem9");
        jMenu16.add(jMenuItem33);

        jMenu5.add(jMenu16);

        jMenu17.setText("Informe Stock");

        jMenuItem34.setText("jMenuItem6");
        jMenu17.add(jMenuItem34);

        jMenuItem35.setText("jMenuItem7");
        jMenu17.add(jMenuItem35);

        jMenuItem36.setText("jMenuItem8");
        jMenu17.add(jMenuItem36);

        jMenuItem37.setText("jMenuItem9");
        jMenu17.add(jMenuItem37);

        jMenu5.add(jMenu17);

        jMenu18.setText("Informe por Sucursal");

        jMenuItem38.setText("jMenuItem6");
        jMenu18.add(jMenuItem38);

        jMenuItem39.setText("jMenuItem7");
        jMenu18.add(jMenuItem39);

        jMenuItem40.setText("jMenuItem8");
        jMenu18.add(jMenuItem40);

        jMenuItem41.setText("jMenuItem9");
        jMenu18.add(jMenuItem41);

        jMenu5.add(jMenu18);

        jMenu19.setText("Informe por Caja");

        jMenuItem42.setText("jMenuItem6");
        jMenu19.add(jMenuItem42);

        jMenuItem43.setText("jMenuItem7");
        jMenu19.add(jMenuItem43);

        jMenuItem44.setText("jMenuItem8");
        jMenu19.add(jMenuItem44);

        jMenuItem45.setText("jMenuItem9");
        jMenu19.add(jMenuItem45);

        jMenu5.add(jMenu19);

        jMenu20.setText("Informe Mercado");

        jMenuItem46.setText("jMenuItem6");
        jMenu20.add(jMenuItem46);

        jMenuItem47.setText("jMenuItem7");
        jMenu20.add(jMenuItem47);

        jMenuItem48.setText("jMenuItem8");
        jMenu20.add(jMenuItem48);

        jMenuItem49.setText("jMenuItem9");
        jMenu20.add(jMenuItem49);

        jMenu5.add(jMenu20);

        jMenu22.setText("Informe por Formato");

        jMenuItem56.setText("jMenuItem6");
        jMenu22.add(jMenuItem56);

        jMenuItem57.setText("jMenuItem7");
        jMenu22.add(jMenuItem57);

        jMenuItem58.setText("jMenuItem8");
        jMenu22.add(jMenuItem58);

        jMenuItem59.setText("jMenuItem9");
        jMenu22.add(jMenuItem59);

        jMenu5.add(jMenu22);

        jMenu24.setText("Informe Anulaciones");

        jMenuItem60.setText("jMenuItem6");
        jMenu24.add(jMenuItem60);

        jMenuItem61.setText("jMenuItem7");
        jMenu24.add(jMenuItem61);

        jMenuItem62.setText("jMenuItem8");
        jMenu24.add(jMenuItem62);

        jMenuItem63.setText("jMenuItem9");
        jMenu24.add(jMenuItem63);

        jMenu5.add(jMenu24);

        jMenu29.setText("Informe por Area");

        jMenuItem78.setText("jMenuItem6");
        jMenu29.add(jMenuItem78);

        jMenuItem79.setText("jMenuItem8");
        jMenu29.add(jMenuItem79);

        jMenuItem80.setText("jMenuItem7");
        jMenu29.add(jMenuItem80);

        jMenuItem81.setText("jMenuItem9");
        jMenu29.add(jMenuItem81);

        jMenu5.add(jMenu29);

        jMenu30.setText("Informe por Linea");

        jMenuItem82.setText("jMenuItem6");
        jMenu30.add(jMenuItem82);

        jMenuItem83.setText("jMenuItem8");
        jMenu30.add(jMenuItem83);

        jMenuItem84.setText("jMenuItem7");
        jMenu30.add(jMenuItem84);

        jMenuItem85.setText("jMenuItem9");
        jMenu30.add(jMenuItem85);

        jMenu5.add(jMenu30);

        jMenuBar1.add(jMenu5);

        jMenu8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu8.setText("RESPALDO");

        jMenuItem12.setText("Backup BD");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Carga BD");
        jMenu8.add(jMenuItem13);

        jMenuBar1.add(jMenu8);

        jMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu2.setText("AYUDA");

        jMenuItem86.setText("Registrar");
        jMenuItem86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem86ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem86);

        jMenuItem11.setText("Acerca de");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu14.setText("SALIR");

        jMenuItem30.setText("Cerrar Sesion");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem30);

        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           try {
               Usuario.desmarcaConexion(Conexion.CONEXION_USERID_OK);
           } catch (Exception ex) {
               Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       
            JOptionPane.showMessageDialog(this, "Desarrollador : Emilio Gajardo. ® ");        
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
          
        frmUsuario pantalla = new frmUsuario(0);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
          
        frmUsuario pantalla = new frmUsuario(1);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
          
        frmUsuario pantalla = new frmUsuario(2);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed

        frmUsuario pantalla = new frmUsuario(3);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void txtOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOperadorActionPerformed

    private void txtSucursalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSucursalMouseEntered
           try {
               Sucursal sucur = new Sucursal(instUsr.getUsu_id_sucu());
               txtSucursal.setToolTipText(sucur.getSuc_nom_suc());
           } catch (SQLException ex) {
               System.out.println("Error : "+ex);
           }
    }//GEN-LAST:event_txtSucursalMouseEntered

    private void txtOperadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOperadorMouseEntered
       
               txtOperador.setToolTipText(instUsr.getUsu_nombres() + 
                       " "+ instUsr.getUsu_apell1() +
                       " "+ instUsr.getUsu_apell2());
    }//GEN-LAST:event_txtOperadorMouseEntered

    private void txtFormatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFormatoMouseEntered
             
           try {
               Formato format = new Formato(instUsr.getUsu_frm_id());                       
               txtFormato.setToolTipText(format.getFrm_slogan() + "    Horario de Atención : " +format.getFrm_hr_ini() +"  hasta las  "+format.getFrm_hr_fin());
               
           } catch (SQLException ex) {
               
           }
    }//GEN-LAST:event_txtFormatoMouseEntered

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
             try {
               Usuario.desmarcaConexion(Conexion.CONEXION_USERID_KO);
               Conexion.desconectar();    
               System.exit(0);
                 } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                 }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           frmCajaVenta cventa = new frmCajaVenta();
           cventa.setLocationRelativeTo(null);
           cventa.setResizable(false);
           cventa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          frmCajaVenta cajaventa = new frmCajaVenta();
          cajaventa.setLocationRelativeTo(null);
          cajaventa.setResizable(false);
          cajaventa.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         frmPPConfig submenu = new frmPPConfig();
         submenu.setLocationRelativeTo(null);
         submenu.setResizable(false);
         submenu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        frmBackup back = new frmBackup();
        back.setLocationRelativeTo(null);
        back.setResizable(false);
        back.setVisible(true);
               
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
       frmSucursal sucur = new frmSucursal(0);
       sucur.setLocationRelativeTo(null);
       sucur.setResizable(false);
       sucur.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       frmSucursal sucur = new frmSucursal(1);
       sucur.setLocationRelativeTo(null);
       sucur.setResizable(false);
       sucur.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
       frmSucursal sucur = new frmSucursal(2);
       sucur.setLocationRelativeTo(null);
       sucur.setResizable(false);
       sucur.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
       frmSucursal sucur = new frmSucursal(3);
       sucur.setLocationRelativeTo(null);
       sucur.setResizable(false);
       sucur.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem86ActionPerformed
       frmRegistrar reg = new frmRegistrar();
       reg.setLocationRelativeTo(null);
       reg.setResizable(false);
       reg.setVisible(true);
    }//GEN-LAST:event_jMenuItem86ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       frmPPGComer submenu = new frmPPGComer();
       submenu.setLocationRelativeTo(null);
       submenu.setResizable(false);
       submenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new frmMenuPrincipal().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtFormato;
    private javax.swing.JTextField txtOperador;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
